version: "1.0"

stages:
  - clone
  - build
  - test

steps:
  main_clone:
    title: Cloning repository...
    stage: clone
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
  build:
    title: Building Docker Image...
    type: build
    image_name: trogo/cloud-utils
    tags: [ 'latest', '0.0.4' ]
    dockerfile: Dockerfile.cloud-utils
    registry: dockerhub
  test:
    title: Testing Docker Image...
    stage: test
    image: trogo/cloud-utils:0.0.4
    commands:
      - terraform --version
      - aws --version
      - python --version
